name: PR

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  validate:
    name: Validate
    runs-on: scaleset-jupiterone-infra-arm64
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Install Dependencies
        run: npm ci --no-scripts
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Install Rebuild
        run: npm rebuild

      - name: Run Validation
        run: npm run validate

      - name: Run Build
        run: npm run build